name: Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Swiftlint
      uses: norio-nomura/action-swiftlint@3.2.1
      with:
        args: --strict

  macos:
    name: macOS
    needs: lint
    runs-on: macos-26
    steps:
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 26
    - name: Checkout
      uses: actions/checkout@v5
      with:
        submodules: true
    - name: Build
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild build-for-testing -scheme ChromaSwift -destination "platform=macOS,arch=arm64" -enableCodeCoverage YES 2>&1 | xcbeautify --renderer github-actions
    - name: Test
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild test-without-building -scheme ChromaSwift -destination "platform=macOS,arch=arm64" -enableCodeCoverage YES 2>&1 | xcbeautify --renderer github-actions
    - name: Codecov upload
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  ios:
    name: iOS
    needs: lint
    runs-on: macos-26
    steps:
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 26
    - name: Checkout
      uses: actions/checkout@v5
      with:
        submodules: true
    - name: Build
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild build-for-testing -scheme ChromaSwift -destination "platform=iOS Simulator,OS=latest,name=iPhone 17" 2>&1 | xcbeautify --renderer github-actions
    - name: Test
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild test-without-building -scheme ChromaSwift -destination "platform=iOS Simulator,OS=latest,name=iPhone 17" 2>&1 | xcbeautify --renderer github-actions

  tvOS:
    name: tvOS
    needs: lint
    runs-on: macos-26
    steps:
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 26
    - name: Checkout
      uses: actions/checkout@v5
      with:
        submodules: true
    - name: Build
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild build-for-testing -scheme ChromaSwift -destination "platform=tvOS Simulator,OS=latest,name=Apple TV" 2>&1 | xcbeautify --renderer github-actions
    - name: Test
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild test-without-building -scheme ChromaSwift -destination "platform=tvOS Simulator,OS=latest,name=Apple TV" 2>&1 | xcbeautify --renderer github-actions
